#!/bin/bash
echo "Welcome to Ancoris Homebrew Package Installer 🥳💻"
REQUIRED_PKG="Homebrew"
PKG_OK=$(brew doctor)
echo Checking for $REQUIRED_PKG: $PKG_OK
if [ "Your system is ready to brew." = "$PKG_OK" ]; then
  echo "$REQUIRED_PKG is installed🍻! Installing packages..."
else
  echo "$REQUIRED_PKG is not installed. Please install $REQUIRED_PKG and then re-run this script :)"
fi
echo "Installing Docker🐳..."
if [ "Your system is ready to brew." = "$PKG_OK" ]; then
  echo "Docker🐳 is already installed!🎉 skipping..."
else
  INSTALL=$(brew install docker)
  echo "$INSTALL"
fi
echo "Installing Ansible👾..."
if [ "" = "" ]; then
  echo "Ansible👾 is already installed!🎉 skipping..."
else
  INSTALL=$(brew install ansible)
  echo "$INSTALL"
fi
echo "Installing git 💻..."
if [ "" = "" ]; then
  echo "git is already installed!🎉 skipping..."
else
  INSTALL=$(brew install git)
  echo "$INSTALL"
fi
echo "Installing gcloud SDK ⌨️ ..."
if [ "" = "" ]; then
  echo "gcloud SDK is already installed!🎉 skipping..."
else
  INSTALL=$(brew install --cask google-cloud-sdk)
  echo "$INSTALL"
fi
echo "Installing gcutil 🤠..."
if [ "" = "" ]; then
  echo "gcutil is already installed!🎉 skipping..."
else
if [ "" = "" ]; then
  echo "Helm is already installed!🎉 skipping..."
else
  INSTALL=$(brew install helm)
  echo "$INSTALL"
fi
echo "Installing Kubernetes🧊..."
if [ "" = "" ]; then
  echo "Kubernetes is already installed!🎉 skipping..."
else
  INSTALL=$(brew install kubernetes-cli@1.22)
  echo "$INSTALL"
fi
echo "Installing Python🐍..."
if [ "" = "" ]; then
  echo "Python is already installed!🎉 skipping..."
else
  INSTALL=$(brew install pyenv)
  echo "$INSTALL"
fi
echo "Installing Terraform🌈..."
if [ "" = "" ]; then
  echo "Terraform is already installed!🎉 skipping..."
else
  INSTALL=$(brew install Terraform)
  echo "$INSTALL"
fi
echo "Installing tfenv🪐..."
  echo "$INSTALL"
fi
echo "Here are all your installed packages:"
brew list
echo "All packages are now installed for you to use!🥳 For a full list of packages visit the Cloud Modernisation Confluence page 💻 Happy Coding! 💻"
