#!/bin/bash  
echo "Welcome to Ancoris Homebrew Package Installer 🥳💻"
REQUIRED_PKG="Homebrew"
PKG_OK=$(brew doctor)
echo Checking for $REQUIRED_PKG: $PKG_OK
if [ "Your system is ready to brew." = "$PKG_OK" ]; then
  echo "$REQUIRED_PKG is installed🍻! Installing packages..."
else
  echo "$REQUIRED_PKG is not installed. Please install $REQUIRED_PKG and then re-run this script :)"
fi
echo "Installing Docker🐳..."
brew install docker

echo "Installing Ansible👾..."
brew install ansible

echo "Installing git 💻..."
brew install git

echo "Installing gcloud SDK ⌨️ ..."
brew install --cask google-cloud-sdk

echo "Installing gcutil 🤠..."
brew install gcutil

echo "Installing Helm..."
brew install helm

echo "Installing Kubernetes🧊..."
brew install kubernetes-cli@1.22

echo "Installing Python🐍..."
brew install pyenv

echo "Installing Terraform🌈..."
brew install tfenv

echo "Here are all your installed packages:"
brew list
echo "All packages are now installed for you to use!🥳 For a full list of packages visit the Cloud Modernisation Confluence page 💻 Happy Coding! 💻"
